apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: ping-pong
spec:
  type: ClusterIP # This is the default value
  selector:
    app: ping-app
  ports:
    - protocol: TCP
      port: 8081 # Port the service is listening on
      targetPort: 8081 # Port the container is listening on (if unset, defaults to equal port value)