apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
  namespace: ping-pong
  labels:
    app: pong-app
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "pong-app"
    tags.datadoghq.com/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "pong-app"
        tags.datadoghq.com/version: "1.0"
    spec:
      containers:
        - name: pong
          #image: northamerica-south1-docker.pkg.dev/bigfito-dev/pingpong-api-mx/pong:1.0
          image: bigfito/pong:1.0
          ports:
            - containerPort: 8082
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
      restartPolicy: Always