# Stage 1: Build the application
FROM maven:3.9-eclipse-temurin-21-alpine AS builder

# Set the working directory inside the container
WORKDIR /build

# Copy the Maven project files
COPY pom.xml ./
COPY ./handler/src ./handler/src
COPY ./handler/pom.xml ./handler/

# Build the application
WORKDIR /build/handler
RUN mvn clean package -DskipTests

WORKDIR /build

# Stage 2: Create a lightweight runtime image
FROM eclipse-temurin:21-jre-alpine

# Define application runtime variables
VOLUME /tmp
EXPOSE 8080

# Copy the application JAR and Datadog Java Agent from the builder stage
COPY --from=builder /build/handler/target/handler-0.0.1-SNAPSHOT.jar /app.jar

# Set the entrypoint command
ENTRYPOINT ["java", "-jar", "/app.jar"]