apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-static-site
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-static-site
  template:
    metadata:
      labels:
        app: apache-static-site
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-content
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: static-content
          configMap:
            name: apache-static-content

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-static-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome</title>
    </head>
    <body>
    <h1>Welcome to My Static Website!</h1>
    <p>This site is served using Apache HTTPD on Kubernetes.</p>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: apache-static-site
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80