apiVersion: v1
kind: Service
metadata:
  name: handler
  namespace: ping-pong
spec:
  type: LoadBalancer # This is the default value
  selector:
    app: handler-app
  ports:
  - protocol: TCP
    port: 8080 # Port the service is listening on
    targetPort: 8080 # Port the container is listening on (if unset, defaults to equal port value)